# Generated by Django 3.2.9 on 2022-01-31 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Courier Name')),
                ('allow_to_cancel', models.BooleanField(default=False, verbose_name='Can Cancel?')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Status Name')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_reference_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='Merchant Reference ID')),
                ('courier_reference_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='Courier Reference ID')),
                ('pickup_name', models.CharField(max_length=128, verbose_name='Sender Name')),
                ('pickup_phone_number', models.CharField(max_length=128, verbose_name='Sender Phone Number')),
                ('pickup_address', models.TextField(verbose_name='Pickup address')),
                ('dropoff_name', models.CharField(max_length=128, verbose_name='Receiver Name')),
                ('dropoff_phone_number', models.CharField(max_length=128, verbose_name='Receiver Phone Number')),
                ('dropoff_address', models.TextField(verbose_name='Drop Off Address')),
                ('canceled', models.BooleanField(default=False, verbose_name='Canceled')),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('courier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.courier', verbose_name='Courier')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='merchant')),
                ('order_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderstatus')),
            ],
        ),
        migrations.CreateModel(
            name='CourierStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_status', models.CharField(max_length=128, verbose_name='Courier Staus')),
                ('courier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.courier', verbose_name='Courier')),
                ('local_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.orderstatus', verbose_name='Local Status')),
            ],
        ),
    ]
